language: scala
jdk:
  - openjdk11
cache:
  directories:
    - $HOME/.ivy2/cache
sudo: false
env:
  - TEST_DIR=2.7/async/akka-examples
  - TEST_DIR=2.7/async/scalatra-atmosphere-embedded
  - TEST_DIR=2.7/async/scalatra-atmosphere-example
  - TEST_DIR=2.7/deployment/scalatra-heroku
  - TEST_DIR=2.7/formats/scalatra-forms
  - TEST_DIR=2.7/http/authentication-demo
  - TEST_DIR=2.7/http/scalatra-gzip
  - TEST_DIR=2.7/http/scalatra-http-demo
  - TEST_DIR=2.7/http/scentry-auth-demo
  - TEST_DIR=2.7/persistence/scalatra-slick
  - TEST_DIR=2.7/persistence/scalatra-squeryl
  - TEST_DIR=2.7/views/scalatra-twirl
  - TEST_DIR=2.7/swagger-example

script: cd $TEST_DIR && sbt test
